### ISSUE TITLE
Timetable not loading

### ISSUE THREAD

**Issue by Tortoise2020** [Railway-Op-Sim/ROSTimetableEditor#12]
Although I can open most of my timetables, I can't seem to open all... (only bought to my attention because I can't open the one I'm working on at the moment)

(Also a sneak peak of Newport, coming soon...)

This is the error message:
<img width="428" alt="Screenshot 2020-02-23 at 23 21 56" src="https://user-images.githubusercontent.com/58140802/75122209-4e2d6300-5693-11ea-9629-470c2c95a8df.png">

These are the files:
[Newport.txt](https://github.com/Railway-Op-Sim/ROSTimetableEditor/files/4242668/Newport.txt)
[26 feb Weekday timetable.txt](https://github.com/Railway-Op-Sim/ROSTimetableEditor/files/4242670/26.feb.Weekday.timetable.txt)

**Comment by zarethrex** [comment]
This issue was due to there being a duplicate service within the timetable given. The program now handles this situation in one of two ways:

If the duplicate is a copy of both ID and start type/start conditions it is ignored.
If the duplicate is a duplicate in ID only then an attempt is made to increment the ID by 1, if this fails the duplicate is ignored.

During the investigation behind this a crash was noted when services containing no stopping locations were included. This has also been fixed.

Both issues resolved in bbbc42d19684a4e1f8984444f5abedbc9d4fa2ac
