### ISSUE TITLE
Program crashes when editing calling points if route (.rly) selected before the timetable.

### ISSUE THREAD

**Issue by Daniel-Gill** [Railway-Op-Sim/ROSTimetableEditor#4]
Selecting the route (using the 'Route' button) before opening the timetable you wish to edit will cause this message to come up if you attempt to edit a calling point:

![image](https://user-images.githubusercontent.com/56364196/74990052-0cee4680-543a-11ea-82cb-0d4cda40c1e4.png)

After pressing OK on this message will cause the program to crash.

What confuses me is that the message suggests, to me, that this should be the order in which this operation is completed.

I have not tested this on other routes or timetables yet.

Please let me know if this is not a bug.

Thanks,
Daniel

**Comment by zarethrex** [comment]
Fixed in d85b93f3966fa4364c109751b51aebecd0426898

Previously the `reset()` function deleted the parser object and as a result deleted the list of stations when a new timetable was opened, thus the app would complain no route was loaded. Now the parser is deleted but the new object is handed a copy of the station list from the previous parser.

Probably not the most efficient way of doing this!
